### ISSUE TITLE
Add `bytecheck` validation to `Archive` types

### ISSUE THREAD

**Issue by bonsairobo** [dimforge/parry#128]
In particular I need `Aabb: CheckBytes<C>`.

Unfortunately I think we will want to wait until a new release of `rkyv` that contains this PR: https://github.com/rkyv/bytecheck/pull/31

We *could* work around that issue by providing a manual `impl`.

**Comment by samlich** [comment]
Fortune!? There are no accidents. I suppose I should've opened a draft before. I've opened #130, but it depends on another change which makes adding a separate bytecheck dependency no longer required. I'm thinking he might make a release after the AlignedVec changes are done, but if not, I can give him a poke.

**Comment by samlich** [comment]
Sorry, I should've got back to this sooner.

@djkoloski, could you consider making a new release of rkyv sometime soon. It's my favoritest crate :pleading_face:.

**Comment by djkoloski** [comment]
Sorry for the delay, 0.7.41 is out now. Does it contain the changes you needed?

**Comment by samlich** [comment]
Yes, many thanks. PR is now marked as ready.
