### ISSUE TITLE
Add MassProperties computation for triangle meshes

### ISSUE THREAD

**Issue by sebcrozet** [dimforge/parry#16]
We should add an automatic computation of triangle-mesh mass properties.
This would implicitly assume that the `TriMesh` is manifold and have consistent winding.

[That paper](http://chenlab.ece.cornell.edu/Publication/Cha/icip01_Cha.pdf) suggests that this should be fairly easy to implement, based on the existing code that computes `ConvexPolyhedron` mass properties.

**Comment by metric-space** [comment]
@sebcrozet  would it be fair to say you you've already implemented this?

**Comment by wlinna** [comment]
I use parry for processing arbitrary (i.e. I can't change the input itself) BIM models, and there's no guarantee that each mesh in a model will be manifold or have consistent winding. I hope these "automatic computations" will stay opt-in, i.e. only computed when `set_flags` is called with specific flag(s).

**Comment by sebcrozet** [comment]
@metric-space Yes, it’s implemented now, this issue can be closed.
@wlinna There is no automatic calculation of the mass properties when the mesh is built. It needs to be calculated using `trimesh.mass_properties()`.
