### ISSUE TITLE
Build fails with --features serde-serialize

### ISSUE THREAD

**Issue by dstaatz** [dimforge/parry#21]
Running `cargo build --features serde-serialize` fails.

Specifically this issue is only for building the parry2d and parry2d-f64 packages.

One of the errors:
```
error[E0277]: the trait bound `ArrayVec<[TrackedContact<ContactData>; 2]>: Deserialize<'_>` is not satisfied
   --> build/parry2d/../../src/query/contact_manifolds/contact_manifold.rs:73:1
```

It seems that the "arrayvec/serde" feature is not enabled when the the serde-serialize feature is enabled.

**Comment by sebcrozet** [comment]
Fixed by #22.
