### ISSUE TITLE
Parry2D errors with "serde" feature enabled

### ISSUE THREAD

**Issue by InnocentusLime** [dimforge/parry#85]
## Issue

Compiling parry 0.9.0 generates a lot of errors about the types used by parry to implementing `Serializable`. All the problematic types can be traced back to `nalgebra`: OPoint, Unit, Matrix

## Steps to reproduce

1. Create an empty project
2. Add `parry2d = { version = "0.9", features = ["serde"] }` to the `Cargo.toml`
3. Run `cargo check`

**Comment by sebcrozet** [comment]
Hi! The feature to enable is `serde-serialize`.

**Comment by InnocentusLime** [comment]
Hello again! `serde-serialize` has fixed it! :)

Although it makes me wonder... Is `Deserialize` unavaliable in parry? Is it going to be available at some point?

**Comment by sebcrozet** [comment]
Serialization and deserialization are both enabled by the `serde-serialize` feature.

**Comment by InnocentusLime** [comment]
Huh! Seems to be the case... The `Collider` type from `bevy_rapier2d` doesn't implement `Deserialize`, so I made wrong assumptions.... Apologies for the wrong report!
